---
- name: Get AWS EC2 Instance IDs
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      "tag:role": "{{ tag_role }}"
  register: ec2_instances

- name: Terminate All AWS EC2 Instances
  ec2:
    region: "{{ region }}"
    instance_ids: "{{ item.instance_id }}"
    state: absent
  with_items: "{{ ec2_instances.instances }}"