---
- name: Check if RHEL
  set_fact:
    tag_role: 'client_rhel'
  when: os_platform == 'rhel'

- name: Check if Ubuntu
  set_fact:
    tag_role: 'client_ubuntu'
  when: os_platform == 'ubuntu'

- name: Check if Amazon Linux
  set_fact:
    tag_role: 'client_amazon-linux'
  when: os_platform == 'amazon-linux'

- name: Get AWS EC2 Instance IDs
  ec2_instance_info:
    region: "{{ region }}"
    filters:
      "tag:role": "{{ tag_role }}"
  register: ec2_instances

- name: Terminate All AWS EC2 Instances
  ec2:
    region: "{{ region }}"
    instance_ids: "{{ item.instance_id }}"
    state: absent
  with_items: "{{ ec2_instances.instances }}"