---
- name: Check if RHEL
  set_fact:
    ami_id: "{{ rhel_ami_id }}"
    instance_tags_name: 'RHEL Client'
    instance_tags_role: 'client_rhel'
  when: os_platform == 'rhel'
- name: Check if Ubuntu
  set_fact:
    ami_id: "{{ ubuntu_ami_id }}"
    instance_tags_name: 'Ubuntu Client'
    instance_tags_role: 'client_ubuntu'
  when: os_platform == 'ubuntu'
- name: Check if Amazon Linux
  set_fact:
    ami_id: "{{ amazonlinux_ami_id }}"
    instance_tags_name: 'Amazon Linux Client'
    instance_tags_role: 'client_amazonlinux'
  when: os_platform == 'amazonlinux'
- name: Starting AWS EC2 Instance
  ec2:
    assign_public_ip: "{{ assign_public_ip }}"
    group_id: "{{ security_group }}"
    image: "{{ ami_id }}"
    instance_tags:
      Name: "{{ instance_tags_name }}"
      role: "{{ instance_tags_role }}"
    instance_type: "{{ type }}"
    key_name: "{{ keypair }}"
    region: "{{ region }}"
    vpc_subnet_id: "{{ subnet }}"