---
- name: Start RHEL 8 AWS EC2 Instance
  ec2:
    assign_public_ip: "{{ assign_public_ip }}"
    group_id: "{{ security_group }}"
    image: "{{ ami_id }}"
    instance_tags:
      Name: "{{ instance_tags_name }}"
      role: "{{ instance_tags_role }}"
    instance_type: "{{ type }}"
    key_name: "{{ keypair }}"
    region: "{{ region }}"
    vpc_subnet_id: "{{ subnet }}"