name: Ansible Lint

on: push

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Lint AWS EC2 Provision Role
      uses: ansible/ansible-lint-action@master
      with:
        targets: "roles/awsec2-provision/tasks"
    - name: Lint AWS EC2 Deprovision Role
      uses: ansible/ansible-lint-action@master
      with:
        targets: "roles/awsec2-deprovision/tasks"
    - name: Lint Root Repository Playbooks
      uses: ansible/ansible-lint-action@master
      with:
        targets: "/"
        args: "-x 301"
